# Generated by Django 5.1.15 on 2026-07-08 00:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchPole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Pôle de l'église",
                'verbose_name_plural': "Pôles de l'église",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyPole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Pôle de la famille',
                'verbose_name_plural': 'Pôles de la famille',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChurchDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='members.churchpole', verbose_name='Pôle')),
            ],
            options={
                'verbose_name': "Département de l'église",
                'verbose_name_plural': "Départements de l'église",
                'ordering': ['pole', 'name'],
                'unique_together': {('name', 'pole')},
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro de membre')),
                ('qr_code', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Code QR')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='Photo')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Postnom')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('profession', models.CharField(blank=True, max_length=150, verbose_name='Profession')),
                ('phone_primary', models.CharField(max_length=20, verbose_name='Téléphone principal')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name='Téléphone secondaire')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('marital_status', models.CharField(choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('divorced', 'Divorcé(e)'), ('widowed', 'Veuf/Veuve')], default='single', max_length=20, verbose_name='Situation matrimoniale')),
                ('is_baptized', models.BooleanField(default=False, verbose_name='Baptisé')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('inactive', 'Inactif'), ('transferred', 'Transféré')], default='active', max_length=20, verbose_name='Statut')),
                ('church_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.churchdepartment', verbose_name="Département de l'église")),
                ('church_pole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.churchpole', verbose_name="Pôle de l'église")),
                ('counsellor', models.ForeignKey(blank=True, limit_choices_to={'role': 'counsellor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_members', to=settings.AUTH_USER_MODEL, verbose_name='Conseiller responsable')),
                ('family_pole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.familypole', verbose_name='Pôle de la famille')),
                ('referrer', models.ForeignKey(blank=True, limit_choices_to={'role': 'referrer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to=settings.AUTH_USER_MODEL, verbose_name='Référent assigné')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MemberHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('action_type', models.CharField(choices=[('created', 'Création'), ('updated', 'Modification'), ('status_changed', 'Changement de statut'), ('assignment', 'Affectation'), ('event_attendance', 'Présence événement'), ('event_absence', 'Absence événement')], max_length=30, verbose_name="Type d'action")),
                ('description', models.TextField(verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='members.member', verbose_name='Membre')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_history_actions', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
            ],
            options={
                'verbose_name': 'Historique membre',
                'verbose_name_plural': 'Historiques membres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_number'], name='members_mem_member__425bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['qr_code'], name='members_mem_qr_code_50a5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['status'], name='members_mem_status_734de0_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['referrer'], name='members_mem_referre_708ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['counsellor'], name='members_mem_counsel_bdec77_idx'),
        ),
    ]
