# Generated by Django 5.1.15 on 2026-07-08 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('events', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event', verbose_name='Événement'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.member', verbose_name='Membre'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='scanned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans_performed', to=settings.AUTH_USER_MODEL, verbose_name='Scanné par'),
        ),
        migrations.AddField(
            model_name='eventagentassignment',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='eventagentassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assigné par'),
        ),
        migrations.AddField(
            model_name='eventagentassignment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to='events.event', verbose_name='Événement'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['event', 'is_present'], name='attendance__event_i_dfcaf4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['member', 'scanned_at'], name='attendance__member__32d739_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('event', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='eventagentassignment',
            unique_together={('event', 'agent')},
        ),
    ]
