# Generated by Django 5.1.15 on 2026-07-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='scan_mode',
            field=models.CharField(blank=True, choices=[('qr', 'QR Code'), ('manual', 'Manuel')], max_length=10, null=True, verbose_name='Mode de pointage'),
        ),
    ]
